### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by R0GGER** [JordanKnott/project-citadel#12]
Hello,

I am running a fresh Citadel in Docker... It looks a bit weird with this font. 
How can I change this?

Screenshot
![000298](https://user-images.githubusercontent.com/8298741/87944051-2eae3100-ca9f-11ea-98fa-6d781dd3d307.png)

**Comment by JordanKnott** [comment]
Citadel uses Droid Sans as it's primary font so if you don't have it installed on your machine it picks a fall back sans-serif font (I think? I didn't actually have any fallback fonts set).

In one of the latest commits, I also have it try to use Roboto if it can't find Droid Sans, otherwise it does pick sans-serif font that it can find.

Eventually I might include the Droid Sans font itself but for the time being it will just use what it can find (Droid Sans > Roboto > sans-serif font).

**Comment by R0GGER** [comment]
Why closed? Bug still exists...
